/* tslint:disable */
/* eslint-disable */
/**
 * Clipboard API
 * REST API for managing clipboard entries
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClipboardDto
 */
export interface ClipboardDto {
    /**
     * 
     * @type {number}
     * @memberof ClipboardDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ClipboardDto
     */
    'localDateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClipboardDto
     */
    'content'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ClipboardDto
     */
    'isPinned'?: boolean;
}

