/* tslint:disable */
/* eslint-disable */
/**
 * Clipboard API
 * REST API for managing clipboard entries
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StopClipboardResponse
 */
export interface StopClipboardResponse {
    /**
     * 
     * @type {boolean}
     * @memberof StopClipboardResponse
     */
    'success'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StopClipboardResponse
     */
    'message'?: string;
}

